--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kroko/Wallpapers/wetcitystreet.png"

-- Special
background="#0a1217"
foreground="#ced0d1"
cursor="#ced0d1"

-- Colors
color0="#0a1217"
color1="#5A5D60"
color2="#A6583F"
color3="#C79B53"
color4="#376C93"
color5="#AA6E8C"
color6="#5896BB"
color7="#ced0d1"
color8="#909192"
color9="#5A5D60"
color10="#A6583F"
color11="#C79B53"
color12="#376C93"
color13="#AA6E8C"
color14="#5896BB"
color15="#ced0d1"
