# Shell variables
# Generated by 'wal'
wallpaper='/home/kroko/Wallpapers/wetcitystreet.png'

# Special
background='#0a1217'
foreground='#ced0d1'
cursor='#ced0d1'

# Colors
color0='#0a1217'
color1='#5A5D60'
color2='#A6583F'
color3='#C79B53'
color4='#376C93'
color5='#AA6E8C'
color6='#5896BB'
color7='#ced0d1'
color8='#909192'
color9='#5A5D60'
color10='#A6583F'
color11='#C79B53'
color12='#376C93'
color13='#AA6E8C'
color14='#5896BB'
color15='#ced0d1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
